apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: ft_services
spec:
  type: LoadBalancer
  externalIPs:
    - 192.168.49.24
  ports:
    - name: grafana
      port: 3000
      protocol: TCP
  selector:
    run: grafana