apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:  
    metallb.universe.tf/allow-shared-ip: 192.168.49.3-192.168.49.3 
  labels:
    app: ft_services
spec:
  type: LoadBalancer
  selector:
    run: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
    - name: https
      protocol: TCP
      port: 443
