apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: ft_services
spec:
  type: LoadBalancer
  externalIPs:
    - 192.168.49.24
  selector:
    run: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
    - name: https
      protocol: TCP
      port: 443
      nodePort: 30443