apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: ft_services
spec:
  type: LoadBalancer
  selector:
    run: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      nodePort: 30080
    - name: https
      protocol: TCP
      port: 443
      nodePort: 30443