apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    run: nginx
    app: ft_services
spec:
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: Never
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          volumeMounts:
            - name: nginx-config-map
              mountPath: /etc/nginx/conf.d/nginx.conf
              subPath: nginx.conf
      restartPolicy: Always
      volumes:
        - name: nginx-config-map
          configMap:
            name: nginx-config-map
