apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  annotations:  
    metallb.universe.tf/allow-shared-ip: 192.168.49.3-192.168.49.3 
  labels:
    app: ft_services
spec:
  type: LoadBalancer
  selector:
    run: phpmyadmin
  ports:
    - protocol: TCP
      port: 5000
