apiVersion: v1
kind: PersistentVolume
metadata:
  name: phpma-volume
  labels:
    run: phpmyadmin
spec:
  storageClassName: phpma
  capacity:
    storage: 600Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/phpmyadmin"