apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: ft_services
spec:
  type: LoadBalancer
  externalIPs:
    - 192.168.49.24
  selector:
    run: phpmyadmin
  ports:
    - protocol: TCP
      port: 5000
