apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: ft_services
spec:
  type: LoadBalancer
  externalIPs:
    - 192.168.49.24
  selector:
    run: wordpress
  ports:
    - name: wordpress
      protocol: TCP
      port: 5050
      targetPort: 5050