apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-volume
  labels:
    run: wordpress
spec:
  storageClassName: wordpress
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/wordpress"
