apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: 192.168.49.3-192.168.49.3
spec:
  type: LoadBalancer
  ports:
    - name: ftps21
      port: 21
    - name: ftps20
      port: 20
    - name: ftps100
      port: 30100
    - name: ftps101
      port: 30101
    - name: ftps102
      port: 30102
    - name: ftps103
      port: 30103
  selector:
    run: ftps
